Selenium in docker compose

diff --git a/.github/workflows/selenium-test.yml b/.github/workflows/selenium-test.yml
--- a/.github/workflows/selenium-test.yml
+++ b/.github/workflows/selenium-test.yml
@@ -1,17 +1,42 @@
-name: Selenium test
+name: Selenium
 
 on:
   push:
+  pull_request:
   workflow_dispatch:
 
 jobs:
-
-  build:
-
+  docker:
+    timeout-minutes: 10
     runs-on: ubuntu-latest
 
     steps:
-    - uses: actions/checkout@v2
+    - name: Checkout
+      uses: actions/checkout@v1
+
+    - name: Start containers
+      run: |
+        cd docker-compose
+        docker-compose -f svjis-dev.yml up -d
+
+    - name: Create schema
+      run: |
+        cd docker-compose
+        curl -k -L -o ./database.sql -L https://raw.githubusercontent.com/svjis/svjis/master/db_schema/database.sql
+        docker cp ./database.sql svjis_db:/firebird/
+        docker cp ./create-schema.sh svjis_db:/firebird/
+        docker exec svjis_db bash "/firebird/create-schema.sh"
+
+    - name: Test
+      run: |
+        string="New Company"
+        if curl -s "http://localhost:8080" | grep -q "$string"; then
+            echo "'$string' found"
+        else
+            curl "http://localhost:8080"
+            echo "'$string' not found"
+            exit 1
+        fi
 
     - name: Install Google Chrome
       run: |
@@ -29,3 +54,9 @@ jobs:
           && sudo mv chromedriver /usr/local/bin/chromedriver \
           && sudo chmod +x /usr/local/bin/chromedriver \
           && chromedriver --version
+
+    - name: Stop containers
+      if: always()
+      run: |
+        cd docker-compose
+        docker-compose -f svjis-dev.yml down
